app/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path(
		route='',
		view=views.Index.as_view(),
		name='index',
	),
]

channels/urls.py
from django.urls import path

from . import views

app_name = 'channels'

urlpatterns = [
	path(
		route='',
		view=views.SearchChannels.as_view(),
		name='search',
	),
	path(
		route='create',
		view=views.CreateChannel.as_view(),
		name='create',
	),
	path(
		route='of-user',
		view=views.UserChannels.as_view(),
		name='of-user',
	),
	path(
		route='<int:pk>',
		view=views.ChannelDetail.as_view(),
		name='detail',
	),
	path(
		route='<int:channel_id>/posts',
		view=views.ChannelPosts.as_view(),
		name='post-list',
	),
	path(
		route='<int:channel_id>/quizes',
		view=views.ChannelQuizes.as_view(),
		name='quizes',
	),
	path(
		route='<int:channel_id>/questions',
		view=views.ChannelQuestions.as_view(),
		name='questions',
	),
	path(
		route='<int:channel_id>/update',
		view=views.UpdateChannel.as_view(),
		name='update',
	),
	path(
		route='<int:channel_id>/subscribe',
		view=views.Subscribe.as_view(),
		name='subscribe',
	),
	path(
		route='<int:channel_id>/unsubscribe',
		view=views.Unsubscribe.as_view(),
		name='unsubscribe',
	),
	path(
		route='<int:channel_id>/control',
		view=views.ChannelControl.as_view(),
		name='control',
	),
	path(
		route='<int:channel_id>/delete',
		view=views.ChannelDeleteView.as_view(),
		name='delete',
	),
	path(
		route='<int:channel_id>/members',
		view=views.ChannelMembers.as_view(),
		name='members',
	),
	path(
		route='about',
		view=views.About.as_view(),
		name='about',
	),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
	path(
		route='<int:post_id>',
		view=views.ShowPost.as_view(),
		name='detail',
	),
	path(
		route='create/assignment/<int:channel_id>',
		view=views.CreateAssignmentPost.as_view(),
		name='create-assignment',
	),
	path(
		route='create/material/<int:channel_id>',
		view=views.CreateLearningMaterialPost.as_view(),
		name='create-material',
	),
	path(
		route='<int:pk>/update-assignment',
		view=views.UpdateAssignmentPost.as_view(),
		name='update-assignment',
	),
	path(
		route='<int:pk>/update-learning',
		view=views.UpdateLearningMaterialPost.as_view(),
		name='update-learning',
	),
	path(
		route='<int:pk>/delete',
		view=views.PostDeleteView.as_view(),
		name='delete',
	),
]

skillthread/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (
	path,
	include,
)

from . import settings

urlpatterns = [
	path(
		route='admin/',
		view=admin.site.urls,
	),
	
	path(
		route='',
		view=include(
			arg='app.urls',
		),
	),
	path(
		route='users/',
		view=include(
			arg='users.urls',
			namespace='users',
		),
	),
	path(
		route='channels/',
		view=include(
			arg='channels.urls',
			namespace='channels',
		),
	),
	path(
		route='posts/',
		view=include(
			arg='posts.urls',
			namespace='posts',
		),
	),
	path(
		route='tests/',
		view=include(
			arg='tests_tests.urls',
			namespace='tests',
		),
	),
	path(
		route='',
		view=include(
			arg='scia.urls',
		),
	),
]

if settings.DEBUG:
	urlpatterns += static(
		settings.MEDIA_URL,
		document_root=settings.MEDIA_ROOT
	)

channels/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class ChannelMembersManager(models.Manager):
	def get_channel_members(self, channel_id):
		# Получаем канал по id
		channel = self.get(id=channel_id)
		
		# Создаем список всех пользователей, связанных с каналом
		users = set()
		
		# Добавляем создателя канала
		users.add(channel.created_by)
		
		# Добавляем авторов канала
		users.update(channel.authors.all())
		
		# Добавляем участников канала
		users.update(channel.participants.all())
		
		return users


class ChannelPopularManager(models.Manager):
	def popular_channels(self):
		return self.order_by('-visits_count')


class Channel(
	models.Model,
):
	# MANAGERS
	objects = models.Manager()
	popular = ChannelPopularManager()
	objects_members = ChannelMembersManager()
	
	# FIELDS
	created_by = models.ForeignKey(
		to=get_user_model(),
		related_name='created_channels',
		on_delete=models.SET_NULL,
		null=True,
	)
	# authors = models.ManyToManyField(
	# 	to=get_user_model(),
	# 	related_name='author_channels',
	# )
	participants = models.ManyToManyField(
		to=get_user_model(),
		related_name='participant_channels',
	)
	image = models.ImageField(
		upload_to='channels/image',
		default='default-channel-image.svg'
	)
	name = models.CharField(
		max_length=255,
		null=False,
	)
	description = models.TextField(
		blank=True,
	)
	visits_count = models.PositiveIntegerField(
		default=0,
	)
	
	def __str__(
		self,
	) -> str:
		return self.name
	
	def increment_visits(self):
		self.visits_count += 1
		self.save()
	
	def get_absolute_url(
		self
	):
		return reverse(
			viewname='channels:detail',
			kwargs={
				'pk': self.id,
			},
		)
	
	class Meta:
		verbose_name = 'Канал'
		verbose_name_plural = 'Каналы'



# class ChannelLink(models.Model):
# 	channel = models.ForeignKey(
# 		to=Channel,
# 		on_delete=models.CASCADE,
# 		related_name="channels_links",
# 	)
# 	url = models.URLField(
# 		max_length=2000,
# 	)
# 	text = models.CharField(
# 		max_length=255,
# 	)
#
# 	def __str__(self):
# 		return self.url
#
# 	class Meta:
# 		verbose_name = 'Ссылка канала'
# 		verbose_name_plural = 'Ссылки каналов'

channels/forms.py
from django import forms

from channels.models import Channel


class ChannelForm(forms.ModelForm):
	name = forms.CharField(
		label='Название',
		widget=forms.TextInput(
			attrs={
				'class': 'form-control',
			},
		),
	)
	description = forms.CharField(
		label='Описание',
		widget=forms.Textarea(
			attrs={
				'class': 'form-control',
				'rows': 1,
			},
		),
		required=False
	)
	image = forms.FileField(
		label='Иконка канала',
		widget=forms.ClearableFileInput(
			attrs={
				'class': 'form-control channel-image',
			},
		),
		required=False
	)
	class Meta:
		model = Channel
		fields = [
			'image',
			'name',
			'description',
		]

channels/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import (
	HttpRequest,
	HttpResponse,
)
from django.shortcuts import (
	get_object_or_404,
	redirect,
	render,
)
from django.urls import (
	reverse,
	reverse_lazy,
)
from django.views import View
from django.views.generic import (
	CreateView,
	DeleteView,
	DetailView,
	ListView,
	TemplateView,
	UpdateView,
)

from channels.forms import ChannelForm
from channels.mixins import (
	ChannelCreatorRequired2Mixin,
	ChannelMembershipRequiredMixin,
	ChannelParticipantRequiredMixin,
	ChannelCreatorRequiredMixin,
)
from channels.models import Channel

app_name = 'channels'


class ChannelPosts(
	LoginRequiredMixin,
	ChannelMembershipRequiredMixin,
	View,
):
	template_name = 'channels/post-list.html'
	
	def get(
		self,
		request,
		channel_id
	):
		channel = get_object_or_404(
			klass=Channel,
			pk=channel_id,
		)
		post_list = channel.posts.all()
		paginator = Paginator(
			object_list=post_list,
			per_page=10,
		)
		page_number = request.GET.get(
			'page'
		)
		page_obj = paginator.get_page(
			page_number
		)
		context = {
			'channel': channel,
			'page_obj': page_obj,
		}
		return render(
			request=request,
			template_name=self.template_name,
			context=context,
		)


class SearchChannels(
	ListView,
):
	model = Channel
	template_name = 'channels/search.html'
	context_object_name = 'channel_list'
	paginate_by = 10
	
	def get_queryset(
		self
	):
		return (
			Channel.popular
			.popular_channels()
			.filter(
				name__icontains=self.request.GET.get(
					'q',
					'',
				),
			)
		)
	
	def get_context_data(
		self,
		*,
		object_list=...,
		**kwargs
	):
		context = super().get_context_data(
			**kwargs
		)
		context['q'] = self.request.GET.get(
			'q'
		)
		return context


class ChannelDetail(
	DetailView,
):
	model = Channel
	template_name = 'channels/detail.html'
	
	def get_object(
		self,
		queryset=None
		):
		channel = super().get_object(
			queryset
		)
		channel.increment_visits()
		return channel


class CreateChannel(
	LoginRequiredMixin,
	CreateView,
):
	model = Channel
	form_class = ChannelForm
	template_name = 'channels/create.html'
	extra_context = {
		'form_title': 'Создание канала',
		'submit_button_inner': 'Создать',
	}
	
	def form_valid(
		self,
		form
	):
		form.instance.created_by = self.request.user
		return super().form_valid(
			form
		)
	
	def get_success_url(
		self
	):
		print(
			self.object.pk
		)
		return reverse(
			viewname='channels:detail',
			kwargs={
				'pk': self.object.pk,
			},
		)


class UpdateChannel(
	LoginRequiredMixin,
	ChannelCreatorRequiredMixin,
	UpdateView,
):
	model = Channel
	form_class = ChannelForm
	template_name = 'channels/update.html'
	extra_context = {
		'form_title': 'Редактирование канала',
		'submit_button_inner': 'Сохранить',
	}
	
	def get_success_url(
		self
	):
		return reverse(
			viewname='channels:detail',
			kwargs={
				'pk': self.object.pk,
			},
		)
	
	def get_object(
		self,
		queryset=...
		):
		channel_id = self.kwargs.get(
			'channel_id'
		)
		return get_object_or_404(
			klass=Channel,
			pk=channel_id,
		)


class UserChannels(
	LoginRequiredMixin,
	TemplateView,
):
	template_name = 'channels/of-user.html'


class Subscribe(
	LoginRequiredMixin,
	View,
):
	def post(
		self,
		request: HttpRequest,
		channel_id: int,
	) -> HttpResponse:
		channel = get_object_or_404(
			klass=Channel,
			pk=channel_id,
		)
		
		channel.participants.add(
			request.user
		)
		
		return redirect(
			to='channels:detail',
			pk=channel.pk,
		)


class Unsubscribe(
	LoginRequiredMixin,
	ChannelParticipantRequiredMixin,
	View,
):
	def post(
		self,
		request: HttpRequest,
		channel_id: int,
	) -> HttpResponse:
		channel = get_object_or_404(
			klass=Channel,
			pk=channel_id,
		)
		
		channel.participants.remove(
			request.user
		)
		
		return redirect(
			to='channels:detail',
			pk=channel.pk,
		)


class ChannelControl(
	LoginRequiredMixin,
	ChannelCreatorRequired2Mixin,
	View,
):
	template_name = 'channels/control.html'
	
	def get(
		self,
		request: HttpRequest,
		channel_id: int,
	) -> HttpResponse:
		channel = get_object_or_404(
			klass=Channel,
			pk=channel_id,
		)
		context = {
			'channel': channel,
		}
		
		return render(
			request=request,
			template_name=self.template_name,
			context=context,
		)

class ChannelDeleteView(
	LoginRequiredMixin,
	ChannelCreatorRequiredMixin,
	DeleteView,
):
	model = Channel
	template_name = 'channels/delete.html'
	success_url = reverse_lazy(
		'channels:of-user'
	)
	
	def get_object(
		self,
		queryset=None
		):
		# Получаем channel_id из URL
		channel_id = self.kwargs.get(
			'channel_id'
		)
		# Получаем объект канала по channel_id
		return get_object_or_404(
			Channel,
			pk=channel_id
		)


class ChannelMembers(
	LoginRequiredMixin,
	ChannelMembershipRequiredMixin,
	TemplateView,
):
	template_name = 'channels/members.html'
	
	def get_context_data(
		self,
		**kwargs
		):
		context = super().get_context_data(
			**kwargs
		)
		
		context['channel'] = Channel.objects.get(
			pk=self.kwargs['channel_id']
		)
		
		return context
	
class About(
	TemplateView,
):
	template_name = 'channels/about.html'


class ChannelQuizes(
	View,
):
	template_name = 'channels/quizes.html'
	def get(
		self,
		request: HttpRequest,
		channel_id: int,
	) -> HttpResponse:
		channel = get_object_or_404(
			klass=Channel,
			id=channel_id,
		)
		post_list = channel.quizes.all()
		paginator = Paginator(
			object_list=post_list,
			per_page=10,
		)
		page_number = request.GET.get(
			'page'
		)
		page_obj = paginator.get_page(
			page_number
		)
		context = {
			'channel': channel,
			'page_obj': page_obj,
		}
		return render(
			request=request,
			template_name=self.template_name,
			context=context,
		)


class ChannelQuestions(
	View,
):
	template_name = 'channels/questions.html'
	def get(
		self,
		request: HttpRequest,
		channel_id: int,
	) -> HttpResponse:
		channel = get_object_or_404(
			klass=Channel,
			id=channel_id,
		)
		questions = channel.questions.all()
		paginator = Paginator(
			object_list=questions,
			per_page=10,
		)
		page_number = request.GET.get(
			'page'
		)
		page_obj = paginator.get_page(
			page_number
		)
		context = {
			'channel': channel,
			'page_obj': page_obj,
		}
		return render(
			request=request,
			template_name=self.template_name,
			context=context,
		)

channels/templates/channels/about.html
{% extends 'app/base.html' %}

{% block content %}
<div class="d-flex flex-column gap-3 align-items-center">
	<h1 align="center">Каналы на SkillThread: Пространство для обмена знаниями</h1>

	<div class="card custom-card">
		<div class="card-body fs-5">
			На платформе SkillThread пользователи могут создавать каналы, где делятся своими знаниями и опытом по различным темам. Эти каналы служат уникальными местами для обучения, где каждый может найти материалы, которые помогут развиваться в выбранной области. Независимо от того, ищете ли вы советы по карьере, практическим навыкам или теоретическим концепциям, на SkillThread всегда найдется канал, который отвечает вашим интересам.
		</div>
	</div>

	<div class="card custom-card">
		<div class="card-body fs-5">
			Каждый канал на SkillThread организован таким образом, чтобы участники могли свободно делиться полезной информацией, задавать вопросы и обмениваться опытом. Взаимодействие в этих пространствах способствует не только получению знаний, но и созданию сообщества, где каждый может внести свой вклад. Каналы помогают людям развивать навыки, расширять кругозор и учиться у других.
			</div>
	</div>
</div>
{% endblock %}

channels/templates/channels/base.html
{% extends 'app/base.html' %}

{% block content %}
	<div class="card channel-header-container {% include 'channels/include/card-class.html' %}">
		<div class="d-flex flex-row justify-content-between g-0 p-3">
			<a href="{% url 'channels:detail' channel.pk %}" class="w-25">
				<img
					class="img-fluid rounded-start"
					src="{{channel.image.url}}"
					alt="Логотип канала"
					style="max-height: 300px"
				>
			</a>
			<div class="card-body d-flex flex-column justify-content-between">
				<h1 class="card-title">{{channel.name}}</h1>
				<div class="d-flex gap-1 flex-wrap">
					{% include 'channels/include/subscribe-button.html' %}
					{% include 'channels/include/go-to-control.html' %}
					{% include 'channels/include/go-to-members.html' %}
					{% include 'channels/include/go-to-posts.html' %}

					{% comment %}
					{% include 'channels/include/go-to-quizes.html' %}
					{% include 'channels/include/go-to-questions.html' %}
					{% endcomment %}
				</div>
			</div>
		</div>
		{% block channel_description %}
		{% endblock %}
		<div class="card-footer text-body-secondary">
			Последнее обновление: {{ channel.posts.first.updated_at }}
		</div>
		{% block channel_card %}
		{% endblock %}
	</div>
	{% block channel_page_content %}
	{% endblock %}
{% endblock %}

channels/templates/channels/card.html
<a href="{{ channel.get_absolute_url }}"
class="d-inline-block mb-3 channel-card-container">
	{% if user == channel.created_by %}
		<div class="card border-primary">
	{% elif user in channel.participants.all %}
		<div class="card border-success">
	{% else %}
		<div class="card">
	{% endif %}
		<div class="card-header d-flex justify-content-between">
			<h5 class="card-title">
				{{ channel.name|truncatechars:50 }}
			</h5>
			<div>
				{% if user == channel.created_by %}
					<span class="text-primary fw-bold">Автор</span>
				{% elif user in channel.participants.all %}
					<span class="text-success fw-bold">Участник</span>
				{% endif %}
			</div>
		</div>
		<div
		class="d-flex flex-row justify-content-start g-0 p-3">
			<img
				src="{{ channel.image.url }}"
				class="img-fluid rounded-start"
				style="max-width: 100px"
			>
			<div class="col-md-8">
				<div class="card-body">
					<p class="card-text">
						{{ channel.description|truncatechars:100 }}
					</p>
				</div>
			</div>
		</div>
		<div class="card-footer d-flex justify-content-between">
			<span>
				Количество просмотров: {{ channel.visits_count }}
			</span>
		</div>
	</div>
</a>

channels/templates/channels/control.html
{% extends 'channels/base.html' %}

{% block channel_page_content %}
	<div class="card custom-card mt-5">
		<div class="card-header">
			<h4 align="center">Управление каналом</h4>
		</div>
		<ul class="list-group list-group-flush">
			<li class="list-group-item">
				<a href="{% url 'channels:update' channel.id %}">
					Редактировать
				</a>
			</li>
			<li class="list-group-item">
				<a href="{% url 'channels:delete' channel.id %}" class="text-danger">
					Удалить канал
				</a>
			</li>
		</ul>
	</div>
{% endblock %}

channels/templates/channels/create.html
{% extends 'app/form.html' %}

{% load static %}

{% block form_title %}
	Создание канала
{% endblock %}

{% block form %}
<div class="d-flex justify-content-center">
	<img id="preview" src="#" alt="Предпросмотр изображения" style="display: none; max-width: 100px; max-height: 100px;"/>
</div>
	{% include 'app/include/form.html' %}
	<script src="{% static 'channels/js/choose-channel-image.js' %}"></script>
{% endblock %}

{% block submit_button_title %}
	Создать канал
{% endblock %}

channels/templates/channels/detail.html
{% extends 'channels/base.html' %}

{% load posts_tags %}

{% block channel_description %}
	{% if channel.description %}
	<div class="card-footer text-body-secondary">
		{{ channel.description }}
	</div>
	{% endif %}
{% endblock %}

{% comment %}
{% block channel_page_content %}
	<div class="card custom-card">

	</div>
{% endblock %}
{% endcomment %}

channels/templates/channels/members.html
{% extends 'channels/base.html' %}

{% load users_tags %}

{% block channel_page_content %}
<div class="card custom-card border-primary text-primary">
	<div class="card-header">
		<h5>Автор</h5>
	</div>
	<ul class="list-group list-group-flush">
		<li class="list-group-item">
			{% show_user_inline channel.created_by %}
		</li>
	</ul>
</div>
<div class="card custom-card border-success text-success">
	<div class="card-header">
		<h5>Участники</h5>
	</div>
	<ul class="list-group list-group-flush">
		{% for participant in channel.participants.all %}
		<li class="list-group-item">
			{% show_user_inline participant %}
		</li>
		{% empty %}
		<li class="list-group-item">
			<span class="opacity-50 fw-bold fs-5 d-flex justify-content-center">Здесь никого нету</span>
		</li>
		{% endfor %}
	</ul>
</div>
{% endblock %}

channels/templates/channels/of-user.html
{% extends 'app/base.html' %}

{% load channels_tags %}

{% block content %}
	<p><h1>Мои каналы</h1></p>
	<p><h2 class="text-primary">Авторство</h2></p>
	{% for channel in request.user.created_channels.all %}
		{% show_channel_card channel user %}
	{% empty %}
		<p>Начните делиться своими знаниями:</p>
		<p><a href="{% url 'channels:create' %}" class="btn btn-primary">Создать свой первый канал</a></p>
	{% endfor %}
	<p><h2 class="text-success">Участие</h2></p>
	{% for channel in request.user.participant_channels.all %}
		{% show_channel_card channel user %}
	{% empty %}
		<p>Начните впитывать "поток умений" от профессионалов:</p>
		<p><a href="{% url 'channels:create' %}" class="btn btn-primary">Найти канал</a></p>
	{% endfor %}
{% endblock %}

channels/templates/channels/post-list.html
{% extends 'channels/base.html' %}

{% load posts_tags %}

{% block channel_content_title %}
	Содержимое канала
{% endblock %}

{% block channel_page_content %}
	<div class="d-flex justify-content-between flex-row m-3 gap-5">
		<h1>
			Посты
		</h1>
		{% if request.user == channel.created_by %}
		<a href="{% url 'posts:create-material' channel.id %}" class="btn btn-primary">
			Добавить учебный материал
		</a>
		{% endif %}
		{% if request.user == channel.created_by %}
		<a href="{% url 'posts:create-assignment' channel.id %}" class="btn btn-primary">
			Добавить тест
		</a>
		{% endif %}
	</div>
	<div class="d-flex flex-column post-list w-100 align-items-center justify-content-center">
		{% include 'app/include/pagination.html' %}
		{% for post in page_obj.object_list %}
			{% show_post_card post %}
		{% empty %}
			{% include 'app/include/clean.html' %}
		{% endfor %}
		{% include 'app/include/pagination.html' %}
	</div>
{% endblock %}

channels/templates/channels/questions.html
{% extends 'channels/base.html' %}

{% load posts_tags %}

{% block channel_content_title %}
Содержимое канала
{% endblock %}

{% block channel_page_content %}
<div class="d-flex justify-content-between flex-row m-3 gap-5">
	<h1>
		Вопросы к тестам
	</h1>
	{% if request.user == channel.created_by %}
	<a href="{% url 'question:create' channel.id %}" class="btn btn-primary">
		Создать вопрос
	</a>
	{% endif %}
</div>
<div class="d-flex flex-column post-list w-100 align-items-center justify-content-center">
	{% include 'app/include/pagination.html' %}
	{% for post in page_obj.object_list %}
	{% show_post_card post %}
	{% empty %}
	{% include 'app/include/clean.html' %}
	{% endfor %}
	{% include 'app/include/pagination.html' %}
</div>
{% endblock %}

channels/templates/channels/quizes.html
{% extends 'channels/base.html' %}

{% load posts_tags %}

{% block channel_content_title %}
	Содержимое канала
{% endblock %}

{% block channel_page_content %}
	<div class="d-flex justify-content-between flex-row m-3 gap-5">
		<h1>
			Тесты канала
		</h1>
		{% if request.user == channel.created_by %}
			<a href="{% url 'quiz:create' channel.id %}" class="btn btn-primary">
				Создать тест
			</a>
		{% endif %}
	</div>
	<div class="d-flex flex-column post-list w-100 align-items-center justify-content-center">
		{% include 'app/include/pagination.html' %}
		{% for post in page_obj.object_list %}
			{% show_post_card post %}
		{% empty %}
			{% include 'app/include/clean.html' %}
		{% endfor %}
		{% include 'app/include/pagination.html' %}
	</div>
{% endblock %}

channels/templates/channels/search-line.html
<form class="d-flex" role="search" method="get" action="{% url 'channels:search' %}">
	<input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Поиск" name="q">
	<button class="btn btn-outline-success" type="submit">Поиск</button>
</form>

channels/templates/channels/search.html
{% extends 'app/base.html' %}

{% load static %}
{% load channels_tags %}

{% block content %}
	<h1 class="d-flex justify-content-center mb-5">
		{% if request.GET.q %}
			Поиск каналов {% if request.GET.q %} по запросу "{{ request.GET.q }}" {% endif %}
		{% else %}
			Популярные каналы
		{% endif %}
	</h1>
	{% include 'channels/search-line.html' %}
	{% if page_obj.paginator.count and request.GET.q %}
	<span class="mt-3 mb-5 fs-5">Результатов поиска: {{ page_obj.paginator.count }}</span>
	{% endif %}
	{% include 'app/include/pagination.html' %}
	<div class="d-flex flex-column channel-list mt-3 w-100 align-items-center">
		{% for channel in channel_list %}
			{% show_channel_card channel user %}
		{% empty %}
			{% include 'app/include/not-found.html' %}
		{% endfor %}
	</div>
	{% include 'app/include/pagination.html' %}
	<button onclick="topFunction()" id="myBtn" title="Go to top"><img
		src="{% static 'app/img/up-arrow-hand-drawn-outline-svgrepo-com.svg' %}" alt="to top" class="img-fluid"></button>
{% endblock %}

channels/templates/channels/update.html
{% extends 'channels/base.html' %}

{% block channel_page_content %}
	{% include 'app/include/form.html' %}
{% endblock %}