app/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path(
		route='',
		view=views.Index.as_view(),
		name='index',
	),
]

channels/urls.py
from django.urls import path

from . import views

app_name = 'channels'

urlpatterns = [
	path(
		route='',
		view=views.SearchChannels.as_view(),
		name='search',
	),
	path(
		route='create',
		view=views.CreateChannel.as_view(),
		name='create',
	),
	path(
		route='of-user',
		view=views.UserChannels.as_view(),
		name='of-user',
	),
	path(
		route='<int:pk>',
		view=views.ChannelDetail.as_view(),
		name='detail',
	),
	path(
		route='<int:channel_id>/posts',
		view=views.ChannelPosts.as_view(),
		name='post-list',
	),
	path(
		route='<int:channel_id>/quizes',
		view=views.ChannelQuizes.as_view(),
		name='quizes',
	),
	path(
		route='<int:channel_id>/questions',
		view=views.ChannelQuestions.as_view(),
		name='questions',
	),
	path(
		route='<int:channel_id>/update',
		view=views.UpdateChannel.as_view(),
		name='update',
	),
	path(
		route='<int:channel_id>/subscribe',
		view=views.Subscribe.as_view(),
		name='subscribe',
	),
	path(
		route='<int:channel_id>/unsubscribe',
		view=views.Unsubscribe.as_view(),
		name='unsubscribe',
	),
	path(
		route='<int:channel_id>/control',
		view=views.ChannelControl.as_view(),
		name='control',
	),
	path(
		route='<int:channel_id>/delete',
		view=views.ChannelDeleteView.as_view(),
		name='delete',
	),
	path(
		route='<int:channel_id>/members',
		view=views.ChannelMembers.as_view(),
		name='members',
	),
	path(
		route='about',
		view=views.About.as_view(),
		name='about',
	),
]

skillthread/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (
	path,
	include,
)

from . import settings

urlpatterns = [
	path(
		route='admin/',
		view=admin.site.urls,
	),
	
	path(
		route='',
		view=include(
			arg='app.urls',
		),
	),
	path(
		route='users/',
		view=include(
			arg='users.urls',
			namespace='users',
		),
	),
	path(
		route='channels/',
		view=include(
			arg='channels.urls',
			namespace='channels',
		),
	),
	path(
		route='posts/',
		view=include(
			arg='posts.urls',
			namespace='posts',
		),
	),
	path(
		route='tests/',
		view=include(
			arg='tests_tests.urls',
			namespace='tests',
		),
	),
	path(
		route='',
		view=include(
			arg='scia.urls',
		),
	),
]

if settings.DEBUG:
	urlpatterns += static(
		settings.MEDIA_URL,
		document_root=settings.MEDIA_ROOT
	)

app/templates/app/include/bootstrap-link.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

app/templates/app/include/bootstrap-script.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

app/templates/app/include/clean.html
{% load static %}

<div class="d-flex flex-column justify-content-center align-items-center opacity-50">
	<img src="{% static 'app/img/clean.svg' %}" alt="clean" class="w-25" style="max-height: 5em">
	<span class="fs-3">Выглядит довольно пусто</span>
</div>

app/templates/app/include/create-first-post-button.html
<a href="{% url 'posts:create' channel.id %}" class="btn btn-primary">
	Создать первый пост
</a>

app/templates/app/include/favicon.html
{% load static %}

<link
	rel="icon"
	href="{% static 'app/img/favicon.png' %}"
	type="image/x-icon"
>

app/templates/app/include/footer.html
<div class="container">
	<footer class="py-5">
		<div class="row">

			<div class="col-6 col-md-3 mb-3">
				<h5>Обзор</h5>
				<ul class="nav flex-column">
					<li class="nav-item mb-2"><a href="{% url 'index' %}" class="nav-link p-0 text-body-secondary">О сайте</a></li>
					<li class="nav-item mb-2"><a href="{% url 'channels:about' %}" class="nav-link p-0 text-body-secondary">О каналах</a></li>
				</ul>
			</div>

			<div class="col-6 col-md-3 mb-3">
				<h5>Контакты</h5>
				<ul class="nav flex-column">
					<li class="nav-item mb-2">Микуцевич Вадим</li>
					<li class="nav-item mb-2">г. Гродно</li>
					<li class="nav-item mb-2">+375 (##) ###-##-##</li>
				</ul>
			</div>
		</div>

		<div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
			<p>© 2024 Company. Все права защищены.</p>
			<ul class="list-unstyled d-flex">
				<li class="ms-3"><a class="link-body-emphasis" href="#">
					<svg class="bi" width="24" height="24">
						<use xlink:href="#twitter"></use>
					</svg>
				</a></li>
				<li class="ms-3"><a class="link-body-emphasis" href="#">
					<svg class="bi" width="24" height="24">
						<use xlink:href="#instagram"></use>
					</svg>
				</a></li>
				<li class="ms-3"><a class="link-body-emphasis" href="#">
					<svg class="bi" width="24" height="24">
						<use xlink:href="#facebook"></use>
					</svg>
				</a></li>
			</ul>
		</div>
	</footer>
</div>

app/templates/app/include/form-footer.html
	<p class="d-flex justify-content-center mt-3">
		<button class="btn btn-primary" type="submit">
			{{ submit_button_inner }}
		</button>
	</p>
</form>

app/templates/app/include/form-header.html
<h2>{{ form_title }}</h2>

<form class="mw-100 mt-3" style="width: 500px" enctype="multipart/form-data" method="post">
	{% csrf_token %}

app/templates/app/include/form.html
{% include 'app/include/form-header.html' %}
	{{ form.as_p }}
{% include 'app/include/form-footer.html' %}

app/templates/app/include/google-fonts.html
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />

app/templates/app/include/main-js-script.html
{% load static %}

<script src="{% static 'app/js/main.js' %}"></script>

app/templates/app/include/messages.html
{% for message in messages %}
<div
	class="
			alert
			{% if message.tags == 'success' %}alert-success{% endif %}
			{% if message.tags == 'info' %}alert-info{% endif %}
			{% if message.tags == 'warning' %}alert-warning{% endif %}
			{% if message.tags == 'error' %}alert-danger{% endif %}
			alert-dismissible show fixed-bottom message-box" role="alert">
	{{ message }}
	<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

app/templates/app/include/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
	<div class="container-fluid">
		<a class="navbar-brand" href="{% url 'index' %}">
			<img
				src="{% static 'app/img/brand.svg' %}"
				alt="brand"
				height="32"
				class="d-inline-block align-text-top"
			>
			SkillThread
		</a>
		<button
			class="navbar-toggler"
			type="button"
			data-bs-toggle="collapse"
			data-bs-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent"
			aria-expanded="false"
			aria-label="Переключатель навигации">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				{% include 'users/include/navbar-dropdown.html' %}
				{% include 'channels/include/navbar-dropdown.html' %}
			</ul>
			{% include 'channels/search-line.html' %}
		</div>
	</div>
</nav>

app/templates/app/include/not-found.html
{% load static %}

<div class="d-flex flex-column justify-content-center align-items-center opacity-50">
	<img src="{% static 'app/img/not-found.svg' %}" alt="clean" class="w-25" style="max-height: 5em">
	<span class="fs-3">Ничего не найдено</span>
</div>